<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AyahGraphApi.Application\AyahGraphApi.Application.csproj" />
      <ProjectReference Include="..\AyahGraphApi.Domain\AyahGraphApi.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Neo4j.Driver" Version="6.3.0" />
    </ItemGroup>

</Project>
